/**
 * React-Antd-Admin-Rest-Api
 * a standard restful api for project react-antd-admin
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The BillionairesNetWorth model module.
* @module model/BillionairesNetWorth
* @version 0.0.0
*/
export default class BillionairesNetWorth {
    /**
    * Constructs a new <code>BillionairesNetWorth</code>.
    * @alias module:model/BillionairesNetWorth
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>BillionairesNetWorth</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BillionairesNetWorth} obj Optional instance to populate.
    * @return {module:model/BillionairesNetWorth} The populated <code>BillionairesNetWorth</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BillionairesNetWorth();

            
            
            

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('trend')) {
                obj['trend'] = ApiClient.convertToType(data['trend'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} value
    */
    value = undefined;
    /**
    * @member {module:model/BillionairesNetWorth.TrendEnum} trend
    */
    trend = undefined;






    /**
    * Allowed values for the <code>trend</code> property.
    * @enum {String}
    * @readonly
    */
    static TrendEnum = {
    
        /**
         * value: "increase"
         * @const
         */
        "increase": "increase",
    
        /**
         * value: "decrease"
         * @const
         */
        "decrease": "decrease",
    
        /**
         * value: "steady"
         * @const
         */
        "steady": "steady"    
    };



}


