/**
 * React-Antd-Admin-Rest-Api
 * a standard restful api for project react-antd-admin
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The UserInfo model module.
* @module model/UserInfo
* @version 0.0.0
*/
export default class UserInfo {
    /**
    * Constructs a new <code>UserInfo</code>.
    * @alias module:model/UserInfo
    * @class
    * @param username {String} 
    * @param password {String} 
    */

    constructor(username, password) {
        

        
        

        this['username'] = username;this['password'] = password;

        
    }

    /**
    * Constructs a <code>UserInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserInfo} obj Optional instance to populate.
    * @return {module:model/UserInfo} The populated <code>UserInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserInfo();

            
            
            

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} username
    */
    username = undefined;
    /**
    * @member {String} password
    */
    password = undefined;








}


