/**
 * React-Antd-Admin-Rest-Api
 * a standard restful api for project react-antd-admin
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ReactAntdAdminRestApi);
  }
}(this, function(expect, ReactAntdAdminRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ReactAntdAdminRestApi.InlineResponse2001();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001', function() {
    it('should create an instance of InlineResponse2001', function() {
      // uncomment below and update the code to test InlineResponse2001
      //var instane = new ReactAntdAdminRestApi.InlineResponse2001();
      //expect(instance).to.be.a(ReactAntdAdminRestApi.InlineResponse2001);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new ReactAntdAdminRestApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property ranking (base name: "ranking")', function() {
      // uncomment below and update the code to test the property ranking
      //var instane = new ReactAntdAdminRestApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property netWorth (base name: "netWorth")', function() {
      // uncomment below and update the code to test the property netWorth
      //var instane = new ReactAntdAdminRestApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property age (base name: "age")', function() {
      // uncomment below and update the code to test the property age
      //var instane = new ReactAntdAdminRestApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property nationality (base name: "nationality")', function() {
      // uncomment below and update the code to test the property nationality
      //var instane = new ReactAntdAdminRestApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property sourceOfWealth (base name: "sourceOfWealth")', function() {
      // uncomment below and update the code to test the property sourceOfWealth
      //var instane = new ReactAntdAdminRestApi.InlineResponse2001();
      //expect(instance).to.be();
    });

  });

}));
