/**
 * React-Antd-Admin-Rest-Api
 * a standard restful api for project react-antd-admin
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BillionairesNetWorth from './model/BillionairesNetWorth';
import BillionairesRanking from './model/BillionairesRanking';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import UserInfo from './model/UserInfo';
import AuthenticationApi from './api/AuthenticationApi';
import BillionairesApi from './api/BillionairesApi';


/**
* a_standard_restful_api_for_project_react_antd_admin.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ReactAntdAdminRestApi = require('index'); // See note below*.
* var xxxSvc = new ReactAntdAdminRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ReactAntdAdminRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ReactAntdAdminRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ReactAntdAdminRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BillionairesNetWorth model constructor.
     * @property {module:model/BillionairesNetWorth}
     */
    BillionairesNetWorth,

    /**
     * The BillionairesRanking model constructor.
     * @property {module:model/BillionairesRanking}
     */
    BillionairesRanking,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The UserInfo model constructor.
     * @property {module:model/UserInfo}
     */
    UserInfo,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The BillionairesApi service constructor.
    * @property {module:api/BillionairesApi}
    */
    BillionairesApi
};
